version: "3"

services:
  db:
    container_name: db
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: digital_bank_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres